---
# sudo ansible-playbook -i "localhost," -c local playbook.yml
# - hosts: all
#   vars:
#     zsh_antigen_bundles_extras:
#       - nvm
#       - joel-porquet/zsh-dircolors-solarized
#     zsh_autosuggestions_bind_key: "^U"
#   roles:
#     - viasite-ansible.zsh

#  sudo ansible-playbook -i inventory.ini -c local playbook.yml
- hosts: localhost
  vars:
    # your extra bundles here
    zsh_antigen_bundles_extras: []
    # your variables here
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - viasite-ansible.zsh
